#!/bin/sh

# wploc  = wallpaper folder                   (eg. /home/aidan/images/wallpapers)
# wpfile = wallpaper file name                (eg. wallpaper.png)
# wpname = wallpaper file name sans extension (eg. wallpaper)

wploc=$(cat ~/.wallp/wploc)
wpfile=$(cat ~/.wallp/wpfile)
wpname=$(cat ~/.wallp/wpname)

i3lock -i $wploc/lock/$wpname.png
