#!/bin/bash

# wploc  = wallpaper folder                   (eg. /home/aidan/images/wallpapers)
# wpfile = wallpaper file name                (eg. wallpaper.png)
# wpname = wallpaper file name sans extension (eg. wallpaper)

wploc=$(cat ~/.wallp/wploc)
wpfile=$(cat ~/.wallp/wpfile)
wpname=$(cat ~/.wallp/wpname)

image=$wploc/$wpfile

width=$(feh -L '%w' $image)
height=$(feh -L '%h' $image)

wratio=$(bc -l <<< "1920 / $width")
hratio=$(bc -l <<< "1080 / $height")

if (( $(bc -l <<< "$wratio > $hratio") )); then
scale=$wratio
w=1
elif (( $(bc -l <<< "$wratio < $hratio") )); then
scale=$hratio
w=0
else
scale=$hratio
fi

scale=$(bc -l <<< "$scale * 100")
scale=$( printf "%.0f" $scale )
scale="$scale%"

convert "$image" -resize 1920x1080^ -gravity center -extent 1920x1080  $wploc/lock/$wpname.png
