#!/bin/bash

wploc="/home/aidanfoley/images/wallpapers"

if [ $# -eq 0 ]; then
	echo "input required"
	exit 1
elif [ $1 = "-l" ]; then
	echo "Listing wallpapers:"
	ls $wploc/*.png
	ls $wploc/*.jpg
elif [ -f "/home/aidanfoley/images/wallpapers/$1.png" ]; then
	echo "Using PNG"
	feh --bg-fill /home/aidanfoley/images/wallpapers/$1.png
	sh ~/scripts/scale_image_to_screen.sh
elif [ -f "/home/aidanfoley/images/wallpapers/$1.jpg" ]; then
	echo "Using JPG"
	feh --bg-fill /home/aidanfoley/images/wallpapers/$1.jpg
	sh ~/scripts/scale_image_to_screen.sh
else
	echo "File /home/aidanfoley/images/wallpapers/$1 not located"
	ls /home/aidanfoley/images/wallpapers
fi
